logging:
  wandb:
    wandb_tag: AIRLfO
    wandb_name_prefix: AIRLfO

algorithm_kwargs:
  demo_batch_size: 64
  gen_replay_buffer_capacity: 1_000_000
  processed_reward_cls: AIRL
  allow_variable_horizon: true
  disc_opt_kwargs:
    lr: 0.0001
    weight_decay: 0

# LfO
reward:
  net_kwargs:
    use_state: true
    use_action: false
    use_next_state: true
    use_done: false
