logging:
  wandb:
    wandb_tag: BC
    wandb_name_prefix: BC
bc:
  batch_size: 128
  l2_weight: 0.0001
  optimizer_cls: !!python/name:torch.optim.adam.Adam ""
  optimizer_kwargs:
    lr: 0.0003
  train_kwargs:
    log_interval: 5000
    log_rollouts_n_episodes: 10
    n_batches: 500_000
    n_epochs: null

environment:
  num_vec: 10
