logging:
  wandb:
    wandb_tag: DePO
    wandb_name_prefix: DePO

algorithm_kwargs:
  demo_batch_size: 64
  gen_replay_buffer_capacity: 1_000_000
  processed_reward_cls: GAIL
  allow_variable_horizon: true
  disc_opt_kwargs:
    lr: 0.0001
    weight_decay: 0
  inv_steps: 1
  inv_batch_size: 256
  inv_lr: 0.0003
  inv_train_interval: 1

# LfO
reward:
  net_kwargs:
    use_state: true
    use_action: false
    use_next_state: true
    use_done: false
