logging:
  wandb:
    wandb_tag: DIFO
    wandb_name_prefix: DIFO

algorithm_kwargs:
  demo_batch_size: 64
  gen_replay_buffer_capacity: 1_000_000
  processed_reward_cls: !!python/name:difo.difo.reward_fn.GAILRewardNetFromDiscriminatorLogit ""
  allow_variable_horizon: true
  disc_opt_kwargs:
    lr: 0.0001
    weight_decay: 0
  mse_positive_weight: 1
  mse_negative_weight: 0
  agent_weight: 0
  expert_weight: 1
  bce_weight: 1
  mse_weight: 1
  logit_scale: 10

# LfO
reward:
  net_kwargs:
    use_state: true
    use_action: false
    use_next_state: true
    use_done: false
