logging:
  wandb:
    wandb_tag: WAIfO
    wandb_name_prefix: WAIfO

algorithm_kwargs:
  demo_batch_size: 64
  gen_replay_buffer_capacity: 1_000_000
  allow_variable_horizon: true
  # WAIL
  regularize_epsilon: 0.001
  disc_grad_clip: 1
  wass_grad_penalty_weight: 0
  disc_opt_kwargs:
    lr: 0.0001
    weight_decay: 0

# LfO
reward:
  net_kwargs:
    use_state: true
    use_action: false
    use_next_state: true
    use_done: false
